name: Publish to PyPI (token)

on:
  push:
    tags:
      - 'v*.*.*'      # v1.2.3
      - '*.*.*'       # 1.2.3
  workflow_dispatch:
    inputs:
      target:
        description: "Where to publish"
        required: true
        default: "pypi"
        type: choice
        options: [pypi, testpypi]

permissions:
  contents: read

jobs:
  build:
    name: Build sdist & wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.13"
      - run: uv venv --python 3.13

      - run: uv pip install build twine

      - name: Build
        run: uv run python -m build

      - name: Twine check
        run: uv run python -m twine check dist/*

      - name: Verify tag matches project.version (only on tag pushes)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          uv run python - <<'PY'
          import os, sys, tomllib, pathlib
          tag = os.environ["GITHUB_REF_NAME"]
          want = tag[1:] if tag.startswith("v") else tag
          data = tomllib.loads(pathlib.Path("pyproject.toml").read_text())
          have = data["project"]["version"]
          if have != want:
              print(f"Tag {tag} != pyproject version {have}", file=sys.stderr)
              sys.exit(1)
          print(f"Version OK: {have}")
          PY

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    # Run when:
    #  - Tag push (normal release), OR
    #  - Manual dispatch with target == pypi
    if: >
      startsWith(github.ref, 'refs/tags/')
      || (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish (PyPI via token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verbose: true
